apiVersion: v1
entries:
  pulsar:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-07-02T06:19:53.443507716Z"
    description: Apache Pulsar Helm chart for Kubernetes
    digest: 2c6b316b1e465302b4ddd4331b3e05625d5b7f212186151b41006180088b8fa8
    home: https://pulsar.apache.org
    icon: http://pulsar.apache.org/img/pulsar.svg
    maintainers:
    - email: dev@pulsar.apache.org
      name: The Apache Pulsar Team
    name: pulsar
    sources:
    - https://github.com/apache/pulsar
    urls:
    - https://github.com/apache/pulsar-helm-chart/releases/download/pulsar-2.6.0/pulsar-2.6.0.tgz
    version: 2.6.0
generated: "2020-07-02T06:19:53.331144753Z"
